### ISSUE TITLE
Add Support for Geometries

### ISSUE THREAD

**Issue by esanya** [makimenko/angular-template-for-threejs#10]
**Is your feature request related to a problem? Please describe.**
I would like to add geometries like (Sphere, Box, Cylinder, Cone, etc)

**Describe the solution you'd like**
I have started by adding a Directive for SphereGeometry like PointLightDirective. But then I get a compiler error: Type 'SphereGeometry' does not satisfy the constraint 'Object3D'. Property 'parent' is missing in type 'SphereGeometry'. 

Yes, that is clear. Geometry is not a Object3D. But what would you consider the correct way?

Do an AbstarctGeometry? Like AbstractObject3D? 

It would be nice to see some Groups of Object too.  How would you implement this?

Thx,
Regards,
Sandor

**Describe alternatives you've considered**

**Additional context**

**Comment by esanya** [comment]
I have found a way. I will add a SphereMeshDirective which can be a subclass of AbstractObject3D....

**Comment by makimenko** [comment]
Hi Sandor,

Great that you found the solution. Sounds good.
Feel free to add new directives to the repository.

Best Regards,

**Comment by ComFreek** [comment]
Partly solved by merged #11.

> It would be nice to see some Groups of Object too. How would you implement this?

- [ ] Still outstanding.

**Comment by makimenko** [comment]
Added EmptyDirective to group objects, add as parent and move meshes together
