### ISSUE TITLE
Raycaster does highlight weirdly in MS Edge

### ISSUE THREAD

**Issue by ComFreek** [makimenko/angular-template-for-threejs#111]
**Describe the bug**
1. Go to https://makimenko.github.io/angular-template-for-threejs/storybook/?path=/story/actor--actors with MS Edge
2. Hover over the servers

**Expected behavior**
![atft-working](https://user-images.githubusercontent.com/11466819/64717622-4dca5280-d4cd-11e9-9c07-8c40e5eab9e0.gif)
(from your recent comment: https://github.com/makimenko/angular-template-for-threejs/pull/108#issuecomment-530466216)

**Screenshots**
![atft-bug](https://user-images.githubusercontent.com/1827709/64858424-9eee5980-d627-11e9-8a89-bdef060bb380.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64-bit
 - Browser: Microsoft Edge 44.18362.267.0

**Comment by makimenko** [comment]
Can't reproduce on my Edge :( tied different sizes and modes... no luck yet.
Microsoft Edge 44.17763.1.0
Microsoft EdgeHTML 18.17763
Windows 10 Pro (1809)

**Comment by makimenko** [comment]
@ComFreek could you please check if left pannel impact on mouse position. If you move cursor to the left similarly to left panel size, then raycaster works, isn't it?

Could you please open full-screen mode and check there?
![image](https://user-images.githubusercontent.com/11466819/65724162-7a2ec300-e0b8-11e9-81d2-c1a841727f63.png)

**Comment by ComFreek** [comment]
> If you move cursor to the left similarly to left panel size, then raycaster works, isn't it?

There's indeed a spurious offset involved, but it's not as wide as the left panel:
![atft-bug-1](https://user-images.githubusercontent.com/1827709/65759330-f8bc4c80-e11a-11e9-9867-97b0d94877fe.gif)

> Could you please open full-screen mode and check there?

Here again we have an offset, albeit a smaller one than in the GIF before:
![atft-bug-2](https://user-images.githubusercontent.com/1827709/65759329-f8bc4c80-e11a-11e9-849c-b5ad0315a850.gif)

**Comment by makimenko** [comment]
@ComFreek Hi. Could you please check now? (I assume there was an issue and was fixed in scope of #141 )

**Comment by ComFreek** [comment]
Yup, it works perfectly! Even hovering over objects far away from the camera works nicely. Thanks for fixing it!
