### ISSUE TITLE
PR #110 Error: Expected 'styles' to be an array of strings.

### ISSUE THREAD

**Issue by makimenko** [makimenko/angular-template-for-threejs#112]
Hi, @ComFreek 
It seems that #110 causing failures in the Storybook:
Error: Expected 'styles' to be an array of strings.

![image](https://user-images.githubusercontent.com/11466819/64859274-7ddf3600-d632-11e9-8c57-717e55d69955.png)

See <https://makimenko.github.io/angular-template-for-threejs/storybook/?path=/story/actor--actors>

**Comment by makimenko** [comment]
Commit temporary reverted.

TODOs:
[ ] Improve build to catch such things
[ ] Upgrade dependency version

**Comment by ComFreek** [comment]
Oh god, I am deeply sorry! I thought Travis would account for it. I searched a bit for "Storybook.js testing": https://storybook.js.org/docs/testing/react-ui-testing/

Seems those snapshots would be a good first try: https://storybook.js.org/docs/testing/structural-testing/

**Comment by makimenko** [comment]
https://github.com/storybookjs/storybook/issues/7877

**Comment by makimenko** [comment]
> Oh god, I am deeply sorry! I thought Travis would account for it. I searched a bit for "Storybook.js testing": https://storybook.js.org/docs/testing/react-ui-testing/
> 
> Seems those snapshots would be a good first try: https://storybook.js.org/docs/testing/structural-testing/

Hm.. I spend 1-2h.. and no success - a bit hard to understand instructions :(
