### ISSUE TITLE
Add badges/CI: Travis CI, automatic push of gh-pages, Greenkeeper, coverage

### ISSUE THREAD

**Issue by ComFreek** [makimenko/angular-template-for-threejs#14]
I heard badges improve a project's perceived quality by users 😄 I'd suggest the following ones:

- [x] Travis CI (+ badge)
- [x] Automatic push of demo, and
- [x] Automatic push of API documentation to gh-pages via Travis CI (@makimenko how did you generate the files in gh-pages? What was the command you ran?)
- [x] Greenkeeper (+ badge)<br>
   (I just `npm install`ed this repo to test it and NPM warned me about "20 vulnerabilities"! Greenkeeper would have prevented that.)
- [x] Maybe coverage (+ badge), but we only have few tests, though. But that could kickoff providing more tests!

See https://github.com/ComFreek/async-playground (shameless self-promotion) or any other repository. Popular repositories tend to have them most.

What do you think? I could do a PR in the next days.

**Comment by makimenko** [comment]
Good Ideas!

Not heard about it, nice to try.

> how did you generate the files in gh-pages? What was the command you ran?

First, need to install globally CLI:
```
npm i -g angular-cli-ghpages
```
then to build as prod deliverable and publish to GitHub pages, run "publish" script from package.json:
```
npm run publish
```
done

**Comment by makimenko** [comment]
> What do you think? I could do a PR in the next days.

Sure, go ahead! I would be very appreciated!

**Comment by ComFreek** [comment]
I've created PR #15. After merging it, please do the following to enable Travis CI & Greenkeeper support:

1. Go to https://github.com/settings/tokens.
2. Add a new token, e.g. with name `makimenko/angular-template-for-threejs Travis CI gh-pages deployment`, copy the token.
3. Go to https://travis-ci.com and log in
4. Add this repository
5. Go to the repository's settings *there*, add a new secure environment variable with name `GITHUB_PAGES_DEPLOYMENT_TOKEN` with the value previously copied.
6. Go to https://greenkeeper.io/, log in and grant the Greenkeeper app access to this repository.

**Comment by makimenko** [comment]
Nice
- steps 1-5 completed
- step 6 in progress

**Comment by ComFreek** [comment]
I'll try to get the PR from Greenkeeper passing!

Is there a specific reason why you changed the URI of the build status image in https://github.com/makimenko/angular-template-for-threejs/commit/85d493ad55fec83fede4c0f582e2ca0eb7bb3cca#diff-04c6e90faac2675aa89e2176d2eec7d8?
I just realized that

- img.shields.io (![](https://img.shields.io/travis/makimenko/angular-template-for-threejs.svg)) defaults to the master branch, thus showing "build passing"
- while the badge from travis considers all branches (?): ![](https://api.travis-ci.com/makimenko/angular-template-for-threejs.svg)
- unless you specify ?branch=master: ![](https://api.travis-ci.com/makimenko/angular-template-for-threejs.svg?branch=master)

Especially the current README shows "build failling" even though only the Greenkeeper build is failing. What do you think about changing it to master-only? (Possibly we can later include a table listing build statuses of every [feature] branch.)

**Comment by ComFreek** [comment]
Hmm, can't get it to work. The problem is with the THREE.js typing imports. I tried:

- `import * as THREE from 'three/index';`: At least VSCode doesn't show any errors anymore, but `ng serve` says `Can't resolve 'three/index'`

- `import * as THREE from 'three';`: Then the types of classes defined in the `examples/js` directory from THREE.js cannot be found. Actually, they should have been exported, though: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/three/index.d.ts

**Comment by makimenko** [comment]
> Is there a specific reason why you changed the URI of the build status image 

Nope, just played around.

> What do you think about changing it to master-only?
Yes, please

> the problem is with the THREE.js typing imports.

I will check later today

**Comment by makimenko** [comment]
Most likely, that version of "three" and "@type/three" should be in sync.
In addition, "three" started to refactor stuff, and it's not reflected in @types yet. But that's a guessing. Will check later.

Workaround: downgraded "three" (to be in in sync with types) and "typescript" (required <3.3.0)

**Comment by makimenko** [comment]
@ComFreek Thanks for ideas!
Now repo looks better and transparent.

**Comment by ComFreek** [comment]
Superb work! I wouldn't have expected a coverage of 92% 😄 

Automatic API push should be done with https://github.com/makimenko/angular-template-for-threejs/commit/0b33a4daba8296bf3bf454455117125e4d1f924f, currently waiting for the Travis build.

**Comment by ComFreek** [comment]
Yay, the latest commit fixed it, see https://makimenko.github.io/angular-template-for-threejs/.
