### ISSUE TITLE
Add Snyk badge to readme

### ISSUE THREAD

**Issue by ComFreek** [makimenko/angular-template-for-threejs#217]
https://support.snyk.io/hc/en-us/articles/360003997277-Badge-Support-for-Repositories suggests using, but that shows (click on it):

[![Snyk badge][link]][link]

Can you perhaps copy some other Snyk badge code, e.g. from the Snyk website for this repo (to which I don't have access), @makimenko?

[link]: https://snyk.io/test/github/makimenko/angular-templates-for-threejs/badge.svg

**Comment by makimenko** [comment]
Hola!
Badge added. Works fine for me.
Please check.

**Comment by ComFreek** [comment]
Gracias!
