### ISSUE TITLE
Trying to publish a package that has been compiled by Ivy. This is not allowed.

### ISSUE THREAD

**Issue by anupamdas2012** [makimenko/angular-template-for-threejs#223]
Hi, im trying to experiment with atft and upload to my own private npm repo. 
npm publish results in an error

"Trying to publish a package that has been compiled by Ivy"
typically ng build atft --prod should fix it but it says no production configuration is available. even though i do see a production config in environment.ts

do i need to disable ivy support?
is there something missing in the environment config?

At the end of the day, Id like to experiment with extending some of these libraries and testing in my own angular projects.

Thanks,

**Comment by makimenko** [comment]
Hello,

Check the project workflows:
https://github.com/makimenko/angular-template-for-threejs/tree/master/.github/workflows

We do ng build atft, then publish. Was working some time ago.

> Id like to experiment with extending some of these libraries

The best way and fast development: `npm run storybook`
This allows dynamically load all newly created components/features.


We would be very appreciated if you can contribute to this repo.

Have a nice day and
Best Regards,

**Comment by makimenko** [comment]
https://github.com/makimenko/angular-template-for-threejs/runs/1122397445?check_suite_focus=true

```
ERROR: Trying to publish a package that has been compiled by Ivy. This is not allowed.
Please delete and rebuild the package, without compiling with Ivy, before attempting to publish.
```

**Comment by makimenko** [comment]
Fixed in:
https://github.com/makimenko/angular-template-for-threejs/releases/tag/1.3.3
