### ISSUE TITLE
WARNING in ColladaLoader 

### ISSUE THREAD

**Issue by sdavarifard** [makimenko/angular-template-for-threejs#24]
I keep on getting: 

WARNING in ./src/app/three-examples/objects/loaders/collada-loader.directive.ts 12:27-46
"export 'ColladaLoader' (imported as 'THREE') was not found in 'three'

WARNING in ./src/app/three-examples/objects/loaders/obj-loader.directive.ts 19:30-45
"export 'MTLLoader' (imported as 'THREE') was not found in 'three'

WARNING in ./src/app/three-examples/objects/loaders/obj-loader.directive.ts 18:27-42
"export 'OBJLoader' (imported as 'THREE') was not found in 'three'

WARNING in ./src/app/three-examples/controls/orbit-controls.directive.ts 55:28-47
"export 'OrbitControls' (imported as 'THREE') was not found in 'three'

i ｢wdm｣: Compiled with warnings.

**Comment by ComFreek** [comment]
@sdavarifard Yes, unfortunately we have to live with these warnings until all of Three.js is refactored into ES modules. I am not a friend of ignoring warnings, either, but do not see a way to solve this issue right away.

**Comment by makimenko** [comment]
Should be fixed now (no warnings anymore).
three >0.103.x released examples as jsm and project switched to it
