### ISSUE TITLE
Basic setup not working

### ISSUE THREAD

**Issue by alexx855** [makimenko/angular-template-for-threejs#367]
## Steps
1.  Create a new angular project `ng new angular-test-atft `
2.  Set up an Angular project and install dependencies as mentioned in the readme: `npm i three three.meshline atft --save`
3.  Import atft  library into your app.module
4.  Add demo atft library components in src/app.component.html
5.  Try to build `ng build`

## Actual Result

```
Warning: Entry point 'atft' contains deep imports into '/home/alexx855/dev/angular-test-atft/node_modules/three/examples/jsm/libs/stats.module.js', '/home/alexx855/dev/angular-test-atft/node_modules/three/examples/jsm/lines/Line2', '/home/alexx855/dev/angular-test-atft/node_modules/three/examples/jsm/lines/LineGeometry', '/home/alexx855/dev/angular-test-atft/node_modules/three/examples/jsm/lines/LineMaterial', '/home/alexx855/dev/angular-test-atft/node_modules/three/examples/jsm/loaders/MTLLoader', '/home/alexx855/dev/angular-test-atft/node_modules/three/examples/jsm/loaders/OBJLoader', '/home/alexx855/dev/angular-test-atft/node_modules/three/examples/jsm/controls/OrbitControls', '/home/alexx855/dev/angular-test-atft/node_modules/three/examples/jsm/postprocessing/RenderPass', '/home/alexx855/dev/angular-test-atft/node_modules/three/examples/jsm/postprocessing/UnrealBloomPass', '/home/alexx855/dev/angular-test-atft/node_modules/three/examples/jsm/postprocessing/EffectComposer', '/home/alexx855/dev/angular-test-atft/node_modules/three/examples/jsm/postprocessing/ShaderPass', '/home/alexx855/dev/angular-test-atft/node_modules/three/examples/jsm/postprocessing/SMAAPass', '/home/alexx855/dev/angular-test-atft/node_modules/three/examples/jsm/shaders/FXAAShader', '/home/alexx855/dev/angular-test-atft/node_modules/three/examples/jsm/postprocessing/BokehPass', '/home/alexx855/dev/angular-test-atft/node_modules/three/examples/jsm/shaders/DotScreenShader', '/home/alexx855/dev/angular-test-atft/node_modules/three/examples/jsm/shaders/VerticalBlurShader', '/home/alexx855/dev/angular-test-atft/node_modules/three/examples/jsm/shaders/HorizontalBlurShader', '/home/alexx855/dev/angular-test-atft/node_modules/three/examples/jsm/postprocessing/Pass'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

Error: The target entry-point "atft" has missing dependencies:
 - dagre
```

i did install dagre as a dev dependency  `npm i dagre  @types/dagre --save-dev` and now the build throw the following error:

```
Error: node_modules/atft/lib/object/abstract-object-3d.d.ts:2:24 - error TS7016: Could not find a declaration file for module 'three'. '/home/alexx855/dev/angular-test-atft/node_modules/three/build/three.js' implicitly has an 'any' type.
  Try `npm install @types/three` if it exists or add a new declaration (.d.ts) file containing `declare module 'three';`
```

So, i did `npm install @types/three --save-dev`

After that, now i'm getting another type errors: 

```
Error: node_modules/atft/lib/raycaster/raycaster-group.directive.d.ts:8:18 - error TS2694: Namespace '"/home/alexx855/dev/angular-test-atft/node_modules/@types/three/index"' has no exported member 'Face3'.

8     face?: THREE.Face3;
                   ~~~~~
node_modules/atft/lib/actor/data-center/layout/dagre-edge.component.d.ts:39:83 - error TS2694: Namespace '"/home/alexx855/dev/angular-test-atft/node_modules/@types/three/index"' has no exported member 'Geometry'.

39     protected getConnectorEndGeometry(type: string): THREE.BufferGeometry | THREE.Geometry;
```

i submitted pr that catch and fix those errors, i think its also related to my previous reported issue.

## Expected Result
Build pass

**Comment by alexx855** [comment]
https://github.com/alexx855/angular-test-atft

**Comment by alexx855** [comment]
im still investigating this, i think we do not need the @types packages, neither the drage one since its only for the examples right?

**Comment by makimenko** [comment]
Hi Alex,

Thanks for looking into it.
> RE:  think we do not need the @types packages, neither the drage

I think dagre used in DagreLayoutComponent (see [storybook](https://makimenko.github.io/angular-template-for-threejs/storybook/?path=/story/dagre-layout-dynamic--dynamic)) for auto-layout. Potentially, could be skipped if not used.
For the @types - package. Most likely three types could be removed from deps (please test if it will not cause issues).

**Comment by alexx855** [comment]
Hi  @makimenko 

I noticed that some errors only are catched when  "enableIvy": true, i did fix most of them, it could be nice to have  "enableIvy": true but i did notice this warning:

`******************************************************************************
It is not recommended to publish Ivy libraries to NPM repositories.
Read more here: https://v9.angular.io/guide/ivy#maintaining-library-compatibility
******************************************************************************`
