### ISSUE TITLE
Raycaster breaks inputs or forms bindings

### ISSUE THREAD

**Issue by alexx855** [makimenko/angular-template-for-threejs#373]
## Steps
1.  Add an input type file, or submit, for example
https://github.com/alexx855/angular-test-atft/blob/master/src/app/app.component.html

## Actual Result
Inputs does not work or biding, having similar issues with angular form radio bindings.
## Expected Result
To work as normal

**Comment by makimenko** [comment]
will be fixed in atft:1.4.22 soon
