### ISSUE TITLE
Clarify differences between atft and this repo

### ISSUE THREAD

**Issue by ComFreek** [makimenko/angular-template-for-threejs#40]
I think we should strive to be as clear as possible to end users what the differences between *this repo* and *atft* are.

I tried to do so in the `2019-04-18-unified-language-in-READMEs` branch, see

- [repo README](https://github.com/makimenko/angular-template-for-threejs/tree/2019-04-18-unified-language-in-READMEs)
- [atft README](https://github.com/makimenko/angular-template-for-threejs/tree/2019-04-18-unified-language-in-READMEs/projects/atft) (as shown in repo under projects/atft & on NPM)

Note that I commented out your basic usage GIF (as shown in https://www.npmjs.com/package/atft/v/0.0.3) resulting from your code:
```html
<atft-orbit-controls [rotateSpeed]=1 [zoomSpeed]=1.2 [listeningControlElement]=mainRenderer.renderPane>
  <atft-webgl-renderer #mainRenderer>
    <atft-perspective-camera [fov]=60 [near]=1 [far]=1100 positionX=20 positionY=50 positionZ=50></atft-perspective-camera>
    <atft-scene>
      <atft-axes-helper size=200></atft-axes-helper>
      <atft-grid-helper size=100 divisions=10></atft-grid-helper>
    </atft-scene>
  </atft-webgl-renderer>
</atft-orbit-controls>
```
I think we should only have one GIF and one demo in the NPM README. Also, it isn't clear how your code above should be run at all. This is what *this* template repo is for, right? But then, we can focus on showing this template's demo alone. Still, showing the basic code above is a good idea in my opinion to attract users. They somehow reach the atft NPM page and see this small code snippet and (hopefully) think "cool, that simple? let's try that".

**What do you think?**

Another thing: Shouldn't this template pull the atft dependency from NPM and not locally from `projects/atft`? If users are to use this template as their starting point, then they should definitely depend on the NPM `atft`.
In an ideal world, we maybe would have two repos: `atft` and `atft-demo-project`. However, now splitting is not an option, I guess. We would lose stars and confuse users even more.

PS: I noticed we have 47 weekly downloads so far on NPM! I didn't download it once! So if they don't all belong to you, we have some real downloaders there 🎆

**Comment by makimenko** [comment]
> I tried to do so in the 2019-04-18-unified-language-in-READMEs branch

Looks nice. Feel free to merge it. 
The only minor recommendation: please format sample code to avoid horizontal scrolling. I think it could be visually better.

> maybe would have two repos: atft and atft-demo-project

Now I like that easy to develop/watch library in one place.  Let's check it a bit later. I think it's Ok to have separate demo for showing this template's demo alone.

> 47 weekly downloads so far on NPM

Yep, nice :)


**Another small thing:**
@ComFreek  I'm trying to add you as NPM atft library maintainer, but seems that email address which is used by you in Git commits (into this repo) - not found in NPM. Could you please share your email address registered in npmjs.com?

**Comment by ComFreek** [comment]
> The only minor recommendation: please format sample code to avoid horizontal scrolling. I think it could be visually better.

- [ ] Will do. 

> Now I like that easy to develop/watch library in one place. 

Indeed, let's stay at that for the moment.

> According to repo traffic stats: 102 Clones, 39 Unique cloners

Oh, I didn't know GitHub showed that. Need to check it out for my repos as well :smile:

> but seems that email address which is used by you in Git commits (into this repo) - not found in NPM

I've just checked. My e-mail address from the latest commits into this repo == the e-mail address for my [NPM profile](https://www.npmjs.com/settings/comfreek/profile) == `['outlook.com', '@', 'comfreek'].reverse().join('')`

**Comment by makimenko** [comment]
Should be Ok now.
Added you as library maintainer on https://www.npmjs.com/package/atft
