### ISSUE TITLE
Failed to initialize Angular compilation - The target entry-point "atft" has missing dependencies : - uuid  - yaml

### ISSUE THREAD

**Issue by barvenikhil** [makimenko/angular-template-for-threejs#421]
## Steps
1. As mentioned on the wiki page i installed the atft using npm and imported the dependency in my project but while running the project I get below error :

./src/main.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Emit attempted before Angular Webpack plugin initialization.

Error: Failed to initialize Angular compilation - The target entry-point "atft" has missing dependencies:
 - uuid
 - yaml

**Comment by makimenko** [comment]
Wiki fixed
