### ISSUE TITLE
Compodoc fails to render code in README.md

### ISSUE THREAD

**Issue by ComFreek** [makimenko/angular-template-for-threejs#44]
See https://makimenko.github.io/angular-template-for-threejs/:

![image](https://user-images.githubusercontent.com/1827709/56714913-7d530b00-6736-11e9-9a0d-c4decbf2f1d6.png)

It's rendered fine on GitHub and NPM, though: https://www.npmjs.com/package/atft

**Comment by makimenko** [comment]
@ComFreek: look-like it's fixed now:
![image](https://user-images.githubusercontent.com/11466819/60995686-abbaac80-a35b-11e9-8eab-205b9b4504b6.png)

**Comment by ComFreek** [comment]
Looks good!
