### ISSUE TITLE
Typo in hightSegments property name of SphereMeshComponent class

### ISSUE THREAD

**Issue by dbelob** [makimenko/angular-template-for-threejs#447]
## Steps
1. Open `SphereMeshComponent` class (`src/lib/object/mesh/sphere-mesh.component.ts` file)
2. Find string `@Input() hightSegments!: number;`

## Actual Result
Property name is `hightSegments`

## Expected Result
Expected name is `heightSegments`

There are 11 `hightSegments` string search result matches in 7 files:
1. src/lib/object/mesh/sphere-mesh.component.ts
2. src/app/app.component.html
3. src/stories/animation/connector/connector-line-animated.stories.ts
4. src/stories/animation/connector/connector-line-bloom.stories.ts
5. src/stories/animation/connector/connector-line.stories.ts
6. src/stories/basic/dynamic/for-loop.stories.ts
7. src/stories/effect/dashed-draw.stories.ts

**Comment by makimenko** [comment]
Fixed typo in atft@1.6.5
