### ISSUE TITLE
Publish Storybook to GitHub Pages

### ISSUE THREAD

**Issue by ComFreek** [makimenko/angular-template-for-threejs#90]
See https://storybook.js.org/docs/basics/exporting-storybook/ on how to export it as a static app.
I think that would be a cool showcase, particularly given your latest PR.

I can do this in the next days if you approve :smile:

**Comment by makimenko** [comment]
Yep, good idea! :)

**Comment by ComFreek** [comment]
@makimenko Here you go: https://makimenko.github.io/angular-template-for-threejs/storybook. It's also mentioned in README now: https://github.com/makimenko/angular-template-for-threejs#storybook

**Comment by makimenko** [comment]
> @makimenko Here you go: https://makimenko.github.io/angular-template-for-threejs/storybook. It's also mentioned in README now: https://github.com/makimenko/angular-template-for-threejs#storybook

Great! Thanks!
